import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e4e2df",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "primary": "#1B2F4E",
        "tertiary-fixed": "#dde1ff",
        "tertiary-container": "#9ba8eb",
        "on-surface-variant": "#4d4637",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#474746",
        "surface-container-high": "#eae8e5",
        "on-background": "#1b1c1a",
        "tertiary-fixed-dim": "#b9c3ff",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary-container": "#e2dfde",
        "on-secondary-fixed": "#1c1b1b",
        "primary-fixed": "#b8cfe0",
        "on-secondary-container": "#636262",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#2e3b77",
        "outline": "#7e7665",
        "inverse-primary": "#94b0cc",
        "primary-fixed-dim": "#94b0cc",
        "tertiary": "#4d5a98",
        "outline-variant": "#d0c5b2",
        "surface-container": "#efeeeb",
        "surface-bright": "#fbf9f6",
        "on-error": "#ffffff",
        "surface": "#fbf9f6",
        "primary-container": "#2d4a6e",
        "secondary": "#5f5e5e",
        "on-primary-container": "#503d00",
        "surface-container-low": "#f5f3f0",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#35437e",
        "on-primary": "#ffffff",
        "surface-tint": "#1B2F4E",
        "inverse-surface": "#30312f",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1c1a",
        "surface-dim": "#dbdad7",
        "on-primary-fixed-variant": "#584400",
        "surface-container-highest": "#e4e2df",
        "on-tertiary-fixed": "#041451",
        "background": "#fbf9f6",
        "on-primary-fixed": "#241a00",
        "inverse-on-surface": "#f2f0ed",
        "navy-accent": "#1B2F4E",
        // Dark mode variants
        "surface-dark": "#1b1c1a",
        "primary-light": "#4a7499",
        "on-surface-variant-dark": "#ccc3b0",
        "surface-container-low-dark": "#2a2b29",
      },
      fontFamily: {
        serif: ["var(--font-playfair)", "Noto Serif", "serif"],
        sans: ["var(--font-inter)", "sans-serif"],
        headline: ["var(--font-playfair)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-inter)"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
